# Dockerfileからイメージビルドしてrailsローカルサーバー起動
# 作成済みイメージが手元にある場合はそれ使う
version: "3"

services:
  nakanaori:
    container_name: nakanaori_container
    build: 
      context: .
      dockerfile: Dockerfile
    image: nakanaori
    volumes:
      - ./:/myapp
    ports:
      - 3000:3000
    command: "rails s -b 0.0.0.0"
    
