# ベースとなるイメージの指定（rubyのバージョン3.0.3を指定）
FROM ruby:2.7

# ビルド時に実行するコマンドの指定
# インストール可能なパッケージの一覧の更新
RUN apt-get update -qq \
# パッケージのインストール（nodejs、postgresql-client、npmを指定）
# && apt-get install -y nodejs mysql-client npm \
&& apt-get install -y nodejs npm \
&& rm -rf /var/lib/apt/lists/* \
&& npm install --global yarn

# 作業ディレクトリの指定
WORKDIR /myapp
# COPY Gemfile Gemfile.lock ./
COPY Gemfile ./
RUN bundle install
# Add a script to be executed every time the container starts.
COPY . .
# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
